---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: randofin-os
# description will be included in the image's metadata
description: This is my personal spin based on the latest bluefin image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - syncthing
        - waydroid
    remove:
      packages:
        - android-tools
        - cockpit-bridge
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-podman
        - cockpit-selinux
        - cockpit-storaged
        - cockpit-system
        - code
        - docker-ce
        - docker-ce-cli
        - docker-ce-rootless-extras
        - docker-compose-plugin
        - docker-model-plugin
        - containerd
        - moby-engine

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - net.waterfox.waterfox
          - com.vscodium.codium
          - org.telegram.desktop
        remove: # replace default Firefox with Waterfox
          - org.mozilla.firefox
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
